#!/bin/sh
PRG="$0"
DIR=`dirname "$PRG"`
PROJECT_ROOT=`cd "$DIR/.." && pwd`
MAVEN_BIN="$PROJECT_ROOT/.tools/apache-maven-3.9.9/bin/mvn"

if [ -f "$MAVEN_BIN" ]; then
    exec "$MAVEN_BIN" "$@"
else
    exec mvn "$@"
fi
